### ISSUE TITLE
App does not start

### ISSUE THREAD

**Issue by unseensholar** [h4h13/Paisa#486] opened 2024-06-18 15:20 UTC
App doesn't start since last update.

**Comment by coutnoah** [comment] 2024-06-19 01:34
Potential duplicate of #480?

**Comment by Golem642** [comment] 2024-06-19 23:00
> Potential duplicate of #480?

Yes it is

**Comment by Daniel-Dan-Espinoza** [comment] 2024-06-21 14:25
It seems so

**Comment by h4h13** [comment] 2024-07-12 19:46
Hey this seams to fixed closing now

**Closed by h4h13** 2024-07-12 19:46 UTC
Labels: bug
