### ISSUE TITLE
Laggy and choppy app experience 

### ISSUE THREAD

**Issue by nisabmohd** [h4h13/Paisa#450] opened 2024-03-08 23:42 UTC
I'm currently using version 6.0.6 and find too many issues feels very laggy when used

**Comment by VarunS2002** [comment] 2024-03-16 02:11
Same here, do you have many transactions added (like more than a hundred)?

**Comment by nisabmohd** [comment] 2024-03-16 03:42
Yes

**Comment by jaredkz** [comment] 2024-03-16 04:00
The cause of the issue has been identified and a fix is in development. It has to do with the way the app deals with larger amounts of transactions.

**Comment by h4h13** [comment] 2024-07-07 18:20
Hey this is fixed closing it

**Closed by h4h13** 2024-07-07 18:20 UTC
